language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: Xihmnw6xrPsEBegz78vkzF95/gV9FLN5exlhtKoy1ZxBT/GmrF/3tpwhhBFINVaIeP5vCwEQJ/PXzCLd6AzoKkCA83u/oY0CufUP+Pt4VsKkom2MiR+yL6WsJRJCNRVXqhTH2RT/SydGsA41YjbE0xjtXK5KNsi6zvx6+UPOFfLax5G5/S2l5s3srvSqk8Ly3vpqyLX8LcfqacranorRRTvl/hlnWQ5W+eQ1+hxjjHQcJctqZ+wZ4kD+Rr/d9XuK86rcpL5G04uGh8ZSKcRMi/+YtJZL4uVTrplf8smeN+CHLyZKsn0LI1b+ZR10nCFmgKTWvamGa2uUsZ9B105mxNx+UyJFKgPEMCC0ASEVVqCVJfMIevWQYHe3OnGDPsiIzmhD9guF1jT3UOI7iasTm4259LjEasID1JVPvGIWMDubRWt1/r9Oc4ii3Fqmf1GXjTpMHhaPCJ+8W+pnd8XlLc6g5eMNKfO6fayFFer5XTrHT6wfdD+Yp0FshWoLiknuoywRSaFci9nK98uNmTAGu3qUJhaD9QMCsaM2vGVP7XD0tzOfaPUL5cH4ixh9YJVK6Mc6d0UupEFeYIDn1aPRQR9Na+0t7uZNBeIYEQd4En4QpA19GiZ8ibhsrs2rp+xFNIJX53VjfmMKsywOCPfAEw86RBcX6wBzMYebCssKOxU=
