name: Homes
version: 0.2
main: com.masahirosaito.spigot.homes.Homes
authors: [MasahiroSaito]
description: This plugin allows each player to set their home point.
website: https://github.com/MasahiroSaito/Homes
commands:
  home:
    description: Main Command of Spigot Plugin Homes
    usage: /home (set)
