name: Homes
version: 0.4
main: com.masahirosaito.spigot.homes.Homes
authors: [MasahiroSaito]
description: This plugin allows each player to set their home point.
website: https://github.com/MasahiroSaito/Homes
commands:
  home:
    description: Homes Command
    usage: /<command> (set)
permissions:
  homes.*:
    description: Grant all permissions of Homes.
    default: op
    children:
      homes.general: true
  homes.general:
    description: Grant general permissions of Homes.
    default: off
    children:
      homes.command: true
      homes.command.name: true
      homes.command.player: true
      homes.command.player.name: true
      homes.command.set: true
      homes.command.set.name: true